config:
  aws:region: us-east-1
  aws:accessKey: test
  aws:secretKey: test
  aws:skipCredentialsValidation: "true"
  aws:skipRequestingAccountId: "true"
  aws:skipMetadataApiCheck: "true"
  aws:s3UsePathStyle: "true"
  aws:endpoints: |
    [{
      "s3": "http://localhost:4566",
      "ec2": "http://localhost:4566",
      "ecs": "http://localhost:4566",
      "ecr": "http://localhost:4566",
      "rds": "http://localhost:4566",
      "elasticache": "http://localhost:4566",
      "iam": "http://localhost:4566",
      "sts": "http://localhost:4566",
      "cloudwatch": "http://localhost:4566",
      "logs": "http://localhost:4566",
      "secretsmanager": "http://localhost:4566",
      "elasticloadbalancingv2": "http://localhost:4566",
      "servicediscovery": "http://localhost:4566"
    }]
  merchant-web-review-infra:environment: local
encryptionsalt: v1:ES24e74Q/A8=:v1:o0b2iwx5vuxX6LPr:OH8brtIQKGe/eyG/YCfWsq5TtUEINA==
