# Generated by Django 6.0.8 on 2026-08-14 07:38

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=255)),
                ('website_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('monitoring_enabled', models.BooleanField(default=False, help_text='If set, this merchant is periodically re-reviewed (Merchant Monitoring).')),
                ('monitoring_interval_hours', models.PositiveIntegerField(default=24)),
            ],
        ),
        migrations.CreateModel(
            name='WebPresenceReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('scraping', 'Gathering Web Presence'), ('analyzing', 'Analyzing Risk Signals'), ('complete', 'Complete'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('is_monitoring_check', models.BooleanField(default=False, help_text='True if this review was triggered by Merchant Monitoring.')),
                ('recommendation', models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail'), ('review', 'Manual Review Recommended')], max_length=10)),
                ('summary', models.TextField(blank=True)),
                ('snapshot_object_key', models.CharField(blank=True, max_length=512)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reviews.merchant')),
            ],
        ),
        migrations.CreateModel(
            name='RiskSignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('domain', 'Domain & Infrastructure'), ('content', 'Site Content & Prohibited Categories'), ('social', 'Social Presence'), ('reputation', 'Online Reputation')], max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Informational'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='info', max_length=10)),
                ('label', models.CharField(max_length=255)),
                ('detail', models.TextField(blank=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='reviews.webpresencereview')),
            ],
        ),
    ]
